cert-manager:
  enabled: {{ .Requirements.ingress.tls.enabled }}
  podAnnotations: 
    "iam.amazonaws.com/role" : "kiam-full-access"
  extraArgs: ["--issuer-ambient-credentials"]
  rbac:
    create: true
  webhook:
    enabled: false
webhook:
  enabled: false
