nginx-ingress:
  ingressClass: "nginx"
  controller:
    scope: 
      enabled: true
      namespace: jx
    replicaCount: 3
    extraArgs:
      publish-service: kube-system/jxing-nginx-ingress-controller
    service:
      omitClusterIP: true
  defaultBackend:
    service:
      omitClusterIP: true
  rbac:
    create: true
